
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Note: `engine` and the `datasource` block are intentionally omitted.
// Declaring `engine: "classic"` makes the PrismaConfig type *require* a
// `datasource: { url: string }` here, and Prisma's env() helper for that url
// throws PrismaConfigEnvError at config-load time if DATABASE_URL is missing
// (e.g. Vercel's install phase, where `prisma generate` runs via postinstall).
// With `engine` omitted, Prisma uses its default schema engine and reads the
// datasource (url + directUrl) straight from prisma/schema.prisma's env().
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
});
