
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Note: the datasource (url + directUrl) is declared in prisma/schema.prisma
// via env(). It is intentionally NOT repeated here — Prisma's env() helper in
// this config file throws at load time if the var is missing, which breaks
// `prisma generate` during the Vercel install phase (where DATABASE_URL isn't
// in scope yet). `generate` doesn't need a DB connection anyway.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
});
